{{- if .Values.dataRepo.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codeforphilly.dataPvcName" . }}
  labels:
    {{- include "codeforphilly.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.dataRepo.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.dataRepo.pvc.size }}
  {{- if .Values.dataRepo.pvc.storageClass }}
  storageClassName: {{ .Values.dataRepo.pvc.storageClass }}
  {{- end }}
{{- end }}
