{{- if and (eq .Values.storage.backend "filesystem") .Values.privateStorage.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codeforphilly.privatePvcName" . }}
  labels:
    {{- include "codeforphilly.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.privateStorage.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.privateStorage.pvc.size }}
  {{- if .Values.privateStorage.pvc.storageClass }}
  storageClassName: {{ .Values.privateStorage.pvc.storageClass }}
  {{- end }}
{{- end }}
